In [ ]:
#irish dataset (flower classification)

In [1]:
%pip install numpy

Requirement already satisfied: numpy in c:\users\pradeepa\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\pradeepa\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pradeepa\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pradeepa\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pradeepa\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pradeepa\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pradeepa\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("IRIS.csv")

In [5]:
print(df.head(10))

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [6]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
df['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [9]:
df.groupby('species')['petal_length'].mean()

species
Iris-setosa        1.464
Iris-versicolor    4.260
Iris-virginica     5.552
Name: petal_length, dtype: float64

In [10]:
df['sepal_length'].max()

7.9

In [12]:
df.sort_values(by='petal_length',ascending=False)

     sepal_length  sepal_width  petal_length  petal_width         species
118           7.7          2.6           6.9          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
..            ...          ...           ...          ...             ...
36            5.5          3.5           1.3          0.2     Iris-setosa
35            5.0          3.2           1.2          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
22            4.6          3.6           1.0          0.2     Iris-setosa

[150 rows x 5 columns]

In [14]:
f=df[df['petal_length']>5]
f

     sepal_length  sepal_width  petal_length  petal_width          species
83            6.0          2.7           5.1          1.6  Iris-versicolor
100           6.3          3.3           6.0          2.5   Iris-virginica
101           5.8          2.7           5.1          1.9   Iris-virginica
102           7.1          3.0           5.9          2.1   Iris-virginica
103           6.3          2.9           5.6          1.8   Iris-virginica
104           6.5          3.0           5.8          2.2   Iris-virginica
105           7.6          3.0           6.6          2.1   Iris-virginica
107           7.3          2.9           6.3          1.8   Iris-virginica
108           6.7          2.5           5.8          1.8   Iris-virginica
109           7.2          3.6           6.1          2.5   Iris-virginica
110           6.5          3.2           5.1          2.0   Iris-virginica
111           6.4          2.7           5.3          1.9   Iris-virginica
112           6.8          3.0           5.5          2.1   Iris-virginica
114           5.8          2.8           5.1          2.4   Iris-virginica
115           6.4          3.2           5.3          2.3   Iris-virginica
116           6.5          3.0           5.5          1.8   Iris-virginica
117           7.7          3.8           6.7          2.2   Iris-virginica
118           7.7          2.6           6.9          2.3   Iris-virginica
120           6.9          3.2           5.7          2.3   Iris-virginica
122           7.7          2.8           6.7          2.0   Iris-virginica
124           6.7          3.3           5.7          2.1   Iris-virginica
125           7.2          3.2           6.0          1.8   Iris-virginica
128           6.4          2.8           5.6          2.1   Iris-virginica
129           7.2          3.0           5.8          1.6   Iris-virginica
130           7.4          2.8           6.1          1.9   Iris-virginica
131           7.9          3.8           6.4          2.0   Iris-virginica
132           6.4          2.8           5.6          2.2   Iris-virginica
133           6.3          2.8           5.1          1.5   Iris-virginica
134           6.1          2.6           5.6          1.4   Iris-virginica
135           7.7          3.0           6.1          2.3   Iris-virginica
136           6.3          3.4           5.6          2.4   Iris-virginica
137           6.4          3.1           5.5          1.8   Iris-virginica
139           6.9          3.1           5.4          2.1   Iris-virginica
140           6.7          3.1           5.6          2.4   Iris-virginica
141           6.9          3.1           5.1          2.3   Iris-virginica
142           5.8          2.7           5.1          1.9   Iris-virginica
143           6.8          3.2           5.9          2.3   Iris-virginica
144           6.7          3.3           5.7          2.5   Iris-virginica
145           6.7          3.0           5.2          2.3   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

In [15]:
df['total_size']=df['sepal_length']+df['petal_length']
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species  \
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

   total_size
0         6.5
1         6.3
2         6.0
3         6.1
4         6.4

In [16]:
f.to_csv('filteres_iris.csv',index=False)

In [ ]:
#convert Pl to numpy array

In [18]:
petal=df['petal_length'].to_numpy()
petal

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [20]:
print('mean', np.mean(petal))
print('median', np.median(petal))
print('sd', np.std(petal))
print('max', np.max(petal))
print('min', np.min(petal))
normalized=(petal-np.min(petal))/(np.max(petal)-np.min(petal))
print(normalized)

mean 3.758666666666666
median 4.35
sd 1.7585291834055212
max 6.9
min 1.0
[0.06779661 0.06779661 0.05084746 0.08474576 0.06779661 0.11864407
 0.06779661 0.08474576 0.06779661 0.08474576 0.08474576 0.10169492
 0.06779661 0.01694915 0.03389831 0.08474576 0.05084746 0.06779661
 0.11864407 0.08474576 0.11864407 0.08474576 0.         0.11864407
 0.15254237 0.10169492 0.10169492 0.08474576 0.06779661 0.10169492
 0.10169492 0.08474576 0.08474576 0.06779661 0.08474576 0.03389831
 0.05084746 0.08474576 0.05084746 0.08474576 0.05084746 0.05084746
 0.05084746 0.10169492 0.15254237 0.06779661 0.10169492 0.06779661
 0.08474576 0.06779661 0.62711864 0.59322034 0.66101695 0.50847458
 0.61016949 0.59322034 0.62711864 0.38983051 0.61016949 0.49152542
 0.42372881 0.54237288 0.50847458 0.62711864 0.44067797 0.57627119
 0.59322034 0.52542373 0.59322034 0.49152542 0.6440678  0.50847458
 0.66101695 0.62711864 0.55932203 0.57627119 0.6440678  0.6779661
 0.59322034 0.42372881 0.47457627 0.45762712 0.49152542 0.69491525
 0.59322034 0.59322034 0.62711864 0.57627119 0.52542373 0.50847458
 0.57627119 0.61016949 0.50847458 0.38983051 0.54237288 0.54237288
 0.54237288 0.55932203 0.33898305 0.52542373 0.84745763 0.69491525
 0.83050847 0.77966102 0.81355932 0.94915254 0.59322034 0.89830508
 0.81355932 0.86440678 0.69491525 0.72881356 0.76271186 0.6779661
 0.69491525 0.72881356 0.76271186 0.96610169 1.         0.6779661
 0.79661017 0.66101695 0.96610169 0.66101695 0.79661017 0.84745763
 0.6440678  0.66101695 0.77966102 0.81355932 0.86440678 0.91525424
 0.77966102 0.69491525 0.77966102 0.86440678 0.77966102 0.76271186
 0.6440678  0.74576271 0.77966102 0.69491525 0.69491525 0.83050847
 0.79661017 0.71186441 0.6779661  0.71186441 0.74576271 0.69491525]

In [ ]:
# 2. netflix movies dataset

In [22]:
d=pd.read_csv('NetflixMovies_dataset.csv')
d

                           Title Name    Language Released Rating    IMDb
0                               "Sr."     English     2022      R     NaN
1                              #Alive      Korean     2020  TV-MA  6.2/10
2                   #FriendButMarried  Indonesian     2018   TV-G  7.1/10
3                 #FriendButMarried 2  Indonesian     2020   TV-G     NaN
4       #OOTD: Outfit of the Designer  Indonesian     2024  TV-14     NaN
...                               ...         ...      ...    ...     ...
4442                   ¡Ay, mi madre!     Spanish     2019  TV-MA  3.8/10
4443                ¡Que viva México!     Spanish     2023      R     NaN
4444      Áfàméfùnà: An Nwa Boi Story         Ibo     2023  TV-14     NaN
4445                          Òlòtūré     English     2019  TV-MA     NaN
4446  Ẹlẹṣin Ọba: The King's Horseman      Yoruba     2022  TV-MA     NaN

[4447 rows x 5 columns]

In [23]:
len(d)

4447

In [6]:
d['Language'].value_counts()

Language
English                                         2236
Spanish                                          352
Hindi                                            339
Japanese                                         141
Indonesian                                       123
                                                ...
Wolof                                              1
Tamil / Hindi / Telegu / Malayalam / Kannada       1
Icelandic                                          1
Albanian                                           1
Ibo                                                1
Name: count, Length: 74, dtype: int64

In [12]:
d.sort_values(by='Released')

                            Title Name    Language Released Rating    IMDb
3480                         The Birds     English     1963  PG-13     NaN
2254                            Marnie     English     1964     PG     NaN
2807                            Prince       Hindi     1969  TV-PG  6.8/10
1148                             Elaan       Hindi     1971  TV-14  6.0/10
1121                        Earthquake     English     1974     PG     NaN
...                                ...         ...      ...    ...     ...
4034    Three Widows Against The World       Malay      NaN  TV-14     NaN
4072                To Love Is To Grow     Spanish      NaN  TV-14     NaN
4260  Violet Evergarden: Recollections    Japanese      NaN  TV-14     NaN
4293   Wave of Cinema: 90's Generation  Indonesian      NaN  TV-PG     NaN
4374                      Wizzo School      Arabic      NaN  TV-14     NaN

[4447 rows x 5 columns]

In [15]:
import pandas as pd
d=pd.read_csv('NetflixMovies_dataset.csv')
print(d['Released'].dtype)

object

In [18]:
d['Released']=pd.to_numeric(d['Released'],errors='coerce')

In [20]:
d['Decade']=(d['Released']//10)*10
print(d.head())

                      Title Name    Language  Released Rating    IMDb  Decade
0                          "Sr."     English    2022.0      R     NaN  2020.0
1                         #Alive      Korean    2020.0  TV-MA  6.2/10  2020.0
2              #FriendButMarried  Indonesian    2018.0   TV-G  7.1/10  2010.0
3            #FriendButMarried 2  Indonesian    2020.0   TV-G     NaN  2020.0
4  #OOTD: Outfit of the Designer  Indonesian    2024.0  TV-14     NaN  2020.0

In [22]:
import numpy as np
avg=np.mean(d['Released'])
avg

np.float64(2018.3418784029038)